version: '3.8'

services:
  postgres:
    container_name: ASFPostgres
    image: postgres:latest
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: asf_user
      POSTGRES_PASSWORD: DJE20ben
      POSTGRES_DB: asf_db
    volumes:
      - ./data:/var/lib/postgresql/data
